from __future__ import annotations  
from typing import Any, Dict, List, Literal, Optional  
from pydantic import BaseModel, ConfigDict, Field 

OfficialWritingType = Literal[  
    "cevap_yazisi",  
    "talep_yazisi", 
    "bilgilendirme_yazisi", 
    "basvuru_cevabi", 
]


class OfficialWritingInput(BaseModel):
    """Normalized Structured Data for the Resmî Yazı Agent."""
    model_config = ConfigDict(extra="forbid")

    # =========================
    # Evrak Analysis
    # =========================

    document_type: Optional[str] = None

    topic: Optional[str] = None
    

    purpose: Optional[str] = None

    intent: Optional[str] = None

    summary: Optional[str] = None

    entities: Dict[str, Any] = Field(default_factory=dict)

    key_information: Dict[str, Any] = Field(default_factory=dict)

    # =========================
    # OCR Metadata
    # =========================

    sayi: Optional[str] = None
    

    tarih: Optional[str] = None

    recipient: Optional[str] = None

    # =========================
    # Routing
    # =========================

    selected_department: Optional[str] = None

    # =========================
    # RAG
    # =========================

    rag: Optional[Dict[str, Any]] = None


class OfficialWritingLLMResponse(BaseModel):

    """Only the body is generated by the LLM."""

    model_config = ConfigDict(extra="forbid")

    body: str = Field(min_length=1)


class OfficialWritingValidation(BaseModel):

    status: Literal["passed", "warning", "rejected"] = "passed"

    issues: List[str] = Field(default_factory=list)


class OfficialWritingPayload(BaseModel):

    generated: bool = False

    type: Optional[OfficialWritingType] = None

    subject: Optional[str] = None

    body: Optional[str] = None

    confidence: float = Field(
        default=0.0,
        ge=0.0,
        le=1.0,
    )

    validation: OfficialWritingValidation = Field(
        default_factory=OfficialWritingValidation
    )


class OfficialWritingAgentResult(BaseModel):

    """Stable public result contract for the final official writing."""

    official_writing: OfficialWritingPayload
