from __future__ import annotations  # تأجيل تقييم الـType Hints
from typing import Any, Dict, List, Literal, Optional  # أنواع البيانات المستخدمة
from pydantic import BaseModel, ConfigDict, Field  # أدوات Pydantic لبناء الـSchemas

OfficialWritingType = Literal[  # أنواع الكتب الرسمية المسموح بها فقط
    "cevap_yazisi",  # كتاب جواب
    "talep_yazisi",  # كتاب طلب
    "bilgilendirme_yazisi",  # كتاب إعلام
    "basvuru_cevabi",  # جواب على طلب/مراجعة
]


class OfficialWritingInput(BaseModel):
    # هذا هو الـStructured Data الذي يستقبله Resmi Yazı Agent
    """Normalized Structured Data for the Resmî Yazı Agent."""
    # بيانات موحدة قادمة من الـAgents السابقة
    model_config = ConfigDict(extra="forbid")
    # يمنع تمرير حقول غير معرفة في الـSchema

    # =========================
    # Evrak Analysis
    # =========================

    document_type: Optional[str] = None
    # نوع الوثيقة القادم من Evrak Analysis

    topic: Optional[str] = None
    # موضوع الوثيقة

    purpose: Optional[str] = None
    # الغرض من الوثيقة

    intent: Optional[str] = None
    # الـIntent الذي حدده Evrak Analysis

    summary: Optional[str] = None
    # ملخص الوثيقة

    entities: Dict[str, Any] = Field(default_factory=dict)
    # الكيانات المستخرجة من الوثيقة

    key_information: Dict[str, Any] = Field(default_factory=dict)
    # المعلومات المهمة المستخرجة من الوثيقة

    # =========================
    # OCR Metadata
    # =========================

    sayi: Optional[str] = None
    # رقم الكتاب إذا كان موجوداً فعلياً في بيانات OCR
    # الـLLM لا يخترعه، وإنما يعرفه فقط إذا كان موجوداً في الـContext

    tarih: Optional[str] = None
    # تاريخ الوثيقة إذا كان موجوداً فعلياً

    recipient: Optional[str] = None
    # الجهة/المخاطَب إذا كانت موجودة في البيانات السابقة

    # =========================
    # Routing
    # =========================

    selected_department: Optional[str] = None
    # الوحدة التي حددها Routing Agent

    # =========================
    # RAG
    # =========================

    rag: Optional[Dict[str, Any]] = None
    # الأساس القانوني القادم من RAG، إذا كان موجوداً


class OfficialWritingLLMResponse(BaseModel):
    # هذا هو الشكل الذي يجب أن يرجعه الـLLM

    """Only the body is generated by the LLM."""
    # الـLLM مسؤول فقط عن الـBody

    model_config = ConfigDict(extra="forbid")
    # يمنع الـLLM من إرجاع حقول إضافية مثل subject أو text

    body: str = Field(min_length=1)
    # النص الرسمي الذي سيُوضع داخل BODY في الـTemplate


class OfficialWritingValidation(BaseModel):
    # نتيجة فحص النص بعد التوليد

    status: Literal["passed", "warning", "rejected"] = "passed"
    # حالة التحقق: ناجح، تحذير، أو مرفوض

    issues: List[str] = Field(default_factory=list)
    # قائمة بالمشاكل التي اكتشفها الـValidator


class OfficialWritingPayload(BaseModel):
    # البيانات النهائية الخاصة بالـResmi Yazı

    generated: bool = False
    # هل تم توليد الكتاب بنجاح؟

    type: Optional[OfficialWritingType] = None
    # نوع الكتاب الرسمي

    subject: Optional[str] = None
    # موضوع الخطاب الرسمي (المطلوب في الـ JSON النهائي)

    body: Optional[str] = None
    # الـBody الذي أنتجه الـLLM

    confidence: float = Field(
        default=0.0,
        ge=0.0,
        le=1.0,
    )
    # درجة الثقة الناتجة عن عملية الـValidation

    validation: OfficialWritingValidation = Field(
        default_factory=OfficialWritingValidation
    )
    # نتيجة التحقق من النص


class OfficialWritingAgentResult(BaseModel):
    # النتيجة العامة التي يرجعها الـResmi Yazı Agent

    """Stable public result contract for the final official writing."""

    official_writing: OfficialWritingPayload
    # وضع كل بيانات الكتاب الرسمي داخل official_writing